import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Footer from "./_components/footer"
import { Toaster } from "sonner"
import { Providers } from "./Providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "CUTIFY - Web App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt" className="dark flex flex-col p-3">
      <body className={inter.className}>
        <Providers>
          {children}
          <Toaster />
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
